import { default as czech } from "@public/main/tours_czech.webp";
import { default as egypt } from "@public/main/tours_egypt.png";
import { default as greece } from "@public/main/tours_greece.webp";
import { default as maldives } from "@public/main/tours_maldives.jpg";
import { default as shymkent } from "@public/main/tours_shymkent.jpg";
import { default as sri_lanka } from "@public/main/tours_sri_lanka.jpg";
import { default as thailand } from "@public/main/tours_thailand.png";
import { default as turkye } from "@public/main/tours_turkye.png";
import { default as uae } from "@public/main/tours_uae.png";
import { Tour } from "./type";

export const allTours: Tour[] = [
  {
    id: 1,
    country: "Турция",
    countryCode: "TR",
    departureCity: "Алматы",
    dateFrom: "2026-06-10",
    dateTo: "2026-06-18",
    startNight: 8,
    endNight: 8,
    rating: 5,
    price: 780000,
    adults: 2,
    children: 1,
    hotelName: "Miracle Resort Hotel",
    city: "Белек",
    image: turkye,
    description:
      "Идеальный семейный отдых на Средиземном море с комфортным пляжным сервисом.",
  },
  {
    id: 2,
    country: "ОАЭ",
    countryCode: "AE",
    departureCity: "Астана",
    dateFrom: "2026-10-05",
    dateTo: "2026-10-12",
    startNight: 7,
    endNight: 7,
    rating: 4,
    price: 650000,
    adults: 2,
    children: 0,
    hotelName: "Rixos Premium Dubai",
    city: "Дубай",
    image: uae,
    description:
      "Современный курорт в Дубае с высоким уровнем сервиса и развитой инфраструктурой.",
  },
  {
    id: 3,
    country: "Египет",
    countryCode: "EG",
    departureCity: "Шымкент",
    dateFrom: "2026-02-15",
    dateTo: "2026-02-25",
    startNight: 10,
    endNight: 10,
    rating: 5,
    price: 590000,
    adults: 2,
    children: 1,
    hotelName: "Sunrise Arabian Beach Resort",
    city: "Хургада",
    image: egypt,
    description:
      "Пляжный отдых с богатым коралловым рифом и отличными условиями для семей.",
  },
  {
    id: 4,
    country: "Таиланд",
    countryCode: "THA",
    departureCity: "Алматы",
    dateFrom: "2026-01-12",
    dateTo: "2026-01-22",
    startNight: 10,
    endNight: 10,
    rating: 4,
    price: 820000,
    adults: 2,
    children: 0,
    hotelName: "Amari Phuket Resort",
    city: "Пхукет",
    image: thailand,
    description:
      "Уютный курорт на побережье Пхукета с живописными видами и спокойным отдыхом.",
  },
  {
    id: 5,
    country: "Мальдивы",
    countryCode: "MDV",
    departureCity: "Астана",
    dateFrom: "2026-03-03",
    dateTo: "2026-03-11",
    startNight: 8,
    endNight: 8,
    rating: 5,
    price: 1950000,
    adults: 2,
    children: 0,
    hotelName: "Adaaran Prestige Vadoo",
    city: "Ваду",
    image: maldives,
    description: "Роскошный отдых на виллах над водой для полного уединения.",
  },
  {
    id: 6,
    country: "Шри-Ланка",
    countryCode: "LKA",
    departureCity: "Алматы",
    dateFrom: "2026-04-18",
    dateTo: "2026-04-27",
    startNight: 9,
    endNight: 9,
    rating: 4,
    price: 720000,
    adults: 2,
    children: 1,
    hotelName: "Cinnamon Bey Beruwala",
    city: "Беруала",
    image: sri_lanka,
    description:
      "Тропический отдых с большим бассейном и разнообразной кухней.",
  },
  {
    id: 7,
    country: "Чехия",
    countryCode: "CZ",
    departureCity: "Алматы",
    dateFrom: "2026-05-10",
    dateTo: "2026-05-17",
    startNight: 7,
    endNight: 7,
    rating: 3,
    price: 530000,
    adults: 2,
    children: 0,
    hotelName: "Hotel Amarilis Prague",
    city: "Прага",
    image: czech,
    description:
      "Комфортное размещение в центре Праги для удобного знакомства с городом.",
  },
  {
    id: 8,
    country: "Греция",
    countryCode: "GRC",
    departureCity: "Астана",
    dateFrom: "2026-06-20",
    dateTo: "2026-06-28",
    startNight: 8,
    endNight: 8,
    rating: 5,
    price: 980000,
    adults: 2,
    children: 0,
    hotelName: "Ikos Olivia",
    city: "Халкидики",
    image: greece,
    description:
      "Премиальный отдых “всё включено” с лучшими пляжами и обслуживанием.",
  },
  {
    id: 9,
    country: "Казахстан",
    countryCode: "KZ",
    departureCity: "Алматы",
    dateFrom: "2026-02-10",
    dateTo: "2026-02-16",
    startNight: 6,
    endNight: 6,
    rating: 4,
    price: 210000,
    adults: 2,
    children: 1,
    hotelName: "Rixos Khadisha Shymkent",
    city: "Шымкент",
    image: shymkent,
    description:
      "Комфортный городской отдых в современном отеле с высоким уровнем сервиса.",
  },
  {
    id: 10,
    country: "Турция",
    countryCode: "TR",
    departureCity: "Астана",
    dateFrom: "2026-09-12",
    dateTo: "2026-09-20",
    startNight: 8,
    endNight: 8,
    rating: 4,
    price: 650000,
    adults: 2,
    children: 0,
    hotelName: "Crystal Deluxe Kemer",
    city: "Кемер",
    image: turkye,
    description: "Спокойный отдых в Кемере рядом с морем и горами.",
  },
  {
    id: 11,
    country: "Египет",
    countryCode: "EG",
    departureCity: "Алматы",
    dateFrom: "2026-11-02",
    dateTo: "2026-11-10",
    startNight: 8,
    endNight: 8,
    rating: 5,
    price: 740000,
    adults: 2,
    children: 2,
    hotelName: "Steigenberger Alcazar",
    city: "Хургада",
    image: egypt,
    description:
      "Пятизвёздочный отдых с просторной территорией и качественным сервисом.",
  },
  {
    id: 12,
    country: "ОАЭ",
    countryCode: "AE",
    departureCity: "Шымкент",
    dateFrom: "2026-12-15",
    dateTo: "2026-12-22",
    startNight: 7,
    endNight: 7,
    rating: 5,
    price: 880000,
    adults: 2,
    children: 1,
    hotelName: "Atlantis The Palm",
    city: "Дубай",
    image: uae,
    description:
      "Знаменитый курорт с аквапарком и развлечениями для всей семьи.",
  },
  {
    id: 13,
    country: "Таиланд",
    countryCode: "THA",
    departureCity: "Астана",
    dateFrom: "2026-04-08",
    dateTo: "2026-04-18",
    startNight: 10,
    endNight: 10,
    rating: 4,
    price: 780000,
    adults: 2,
    children: 0,
    hotelName: "The Nature Phuket",
    city: "Пхукет",
    image: thailand,
    description:
      "Современный курорт рядом с пляжем и зелёной природой Пхукета.",
  },
  {
    id: 14,
    country: "Италия",
    countryCode: "ITA",
    departureCity: "Шымкент",
    dateFrom: "2026-07-01",
    dateTo: "2026-07-10",
    startNight: 9,
    endNight: 9,
    rating: 4,
    price: 1150000,
    adults: 2,
    children: 0,
    hotelName: "Hotel Touring Rimini",
    city: "Римини",
    image: thailand,
    description: "Уютный отель у моря для комфортного отдыха на Адриатике.",
  },
  {
    id: 15,
    country: "Греция",
    countryCode: "GRC",
    departureCity: "Астана",
    dateFrom: "2026-05-18",
    dateTo: "2026-05-28",
    startNight: 10,
    endNight: 10,
    rating: 5,
    price: 1030000,
    adults: 2,
    children: 1,
    hotelName: "Creta Maris Resort",
    city: "Крит",
    image: thailand,
    description: "Большой семейный курорт с красивыми пляжами и активностями.",
  },
  {
    id: 16,
    country: "Чехия",
    countryCode: "CZ",
    departureCity: "Астана",
    dateFrom: "2026-10-01",
    dateTo: "2026-10-08",
    startNight: 7,
    endNight: 7,
    rating: 3,
    price: 490000,
    adults: 2,
    children: 0,
    hotelName: "Hotel Legie Prague",
    city: "Прага",
    image: thailand,
    description: "Практичный вариант для недорогого отдыха в центре Праги.",
  },
  {
    id: 17,
    country: "Мальдивы",
    countryCode: "MDV",
    departureCity: "Алматы",
    dateFrom: "2026-02-20",
    dateTo: "2026-02-28",
    startNight: 8,
    endNight: 8,
    rating: 5,
    price: 2100000,
    adults: 2,
    children: 0,
    hotelName: "Sun Siyam Iru Veli",
    city: "Иру Вели",
    image: thailand,
    description:
      "Премиальный островной курорт с частными пляжами и спокойным отдыхом.",
  },
  {
    id: 18,
    country: "Вьетнам",
    countryCode: "VN",
    departureCity: "Алматы",
    dateFrom: "2026-06-05",
    dateTo: "2026-06-15",
    startNight: 10,
    endNight: 10,
    rating: 4,
    price: 780000,
    adults: 2,
    children: 0,
    hotelName: "Fusion Resort Phu Quoc",
    city: "Фукуок",
    image: thailand,
    description:
      "Современный курорт на острове Фукуок с уютными виллами и пляжными развлечениями.",
  },
  {
    id: 19,
    country: "Китай",
    countryCode: "CN",
    departureCity: "Астана",
    dateFrom: "2026-09-10",
    dateTo: "2026-09-20",
    startNight: 10,
    endNight: 10,
    rating: 4,
    price: 850000,
    adults: 2,
    children: 0,
    hotelName: "The Ritz-Carlton Beijing",
    city: "Пекин",
    image: thailand,
    description: "Элегантный отель в центре Пекина с комфортными номерами.",
  },
  {
    id: 20,
    country: "Катар",
    countryCode: "QA",
    departureCity: "Алматы",
    dateFrom: "2026-12-01",
    dateTo: "2026-12-10",
    startNight: 9,
    endNight: 9,
    rating: 5,
    price: 1250000,
    adults: 2,
    children: 0,
    hotelName: "Marsa Malaz Kempinski",
    city: "Доха",
    image: thailand,
    description: "Роскошный отель в Дохе с видом на Персидский залив.",
  },
];
