import AppFrame from "@/components/AppFrame";
import type { Metadata } from "next";
import styles from "./body.module.scss";
import { manrope, pt_serif } from "./fonts";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${pt_serif.variable} ${styles.container}`}
      >
        <AppFrame>{children}</AppFrame>
      </body>
    </html>
  );
}
